package com.project.model;// default package
// Generated Nov 23, 2017 7:42:03 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CartId generated by hbm2java
 */
@Embeddable
public class CartId implements java.io.Serializable {

	private int customersid;
	private int productid;

	public CartId() {
	}

	public CartId(int customersid, int productid) {
		this.customersid = customersid;
		this.productid = productid;
	}

	@Column(name = "customersid", nullable = false)
	public int getCustomersid() {
		return this.customersid;
	}

	public void setCustomersid(int customersid) {
		this.customersid = customersid;
	}

	@Column(name = "productid", nullable = false)
	public int getProductid() {
		return this.productid;
	}

	public void setProductid(int productid) {
		this.productid = productid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CartId))
			return false;
		CartId castOther = (CartId) other;

		return (this.getCustomersid() == castOther.getCustomersid())
				&& (this.getProductid() == castOther.getProductid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCustomersid();
		result = 37 * result + this.getProductid();
		return result;
	}

}
