package com.project.model;// default package
// Generated Nov 23, 2017 7:42:03 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Payment generated by hbm2java
 */
@Entity
public class Payment implements java.io.Serializable {

	private Integer id;
	private String paymentType;
	private String transactionid;
	private Integer allowed;
	private Set<Orders> orderses = new HashSet<Orders>(0);

	public Payment() {
	}

    public String getTransactionid() {
        return transactionid;
    }

    public void setTransactionid(String transactionid) {
        this.transactionid = transactionid;
    }

    public Payment(String paymentType, Integer allowed , String transaction_id, Set<Orders> orderses) {
		this.paymentType = paymentType;
		this.allowed = allowed;
		this.orderses = orderses;
	this.transactionid=transaction_id;

	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "paymentType")
	public String getPaymentType() {
		return this.paymentType;
	}

	public void setPaymentType(String paymentType) {
		this.paymentType = paymentType;
	}

	@Column(name = "allowed")
	public Integer getAllowed() {
		return this.allowed;
	}

	public void setAllowed(Integer allowed) {
		this.allowed = allowed;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "payment")
	public Set<Orders> getOrderses() {
		return this.orderses;
	}

	public void setOrderses(Set<Orders> orderses) {
		this.orderses = orderses;
	}

}
